packages: []

savePrefix: ""
minimumReleaseAge: 10080
minimumReleaseAgeExclude: []
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
trustLockfile: false
blockExoticSubdeps: true
